config/routes.rb
Rails.application.routes.draw do

  resources :products, only: [:index, :show]
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  resources :users do
    resources :products, controller: 'users/products'
  end

  get   '/login' => 'sessions#new'
  post  '/login' => 'sessions#create'
  get   '/logout' => 'sessions#destroy'

  get   'home/index'

  root  'home#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  validates :name, :price, :image_url, :user_id, presence: true
  validates :price, numericality: { greater_than: 0 }

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :user_name, :email, :password, :password_confirmation, presence: true
  validates :user_name, :email, uniqueness: true
  validates_length_of :password, minimum: 6
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :user_name, format: { without: /\s/ }
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    unless current_user
      flash[:danger] = 'Log in first'
      redirect_to login_path
    end

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authorize
  before_action :set_product, only: [:show]

  def index
    @products = Product.all
  end

  def show
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user =  User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = 'User login'
      redirect_to root_path
    else
      flash[:alert] = 'Invalid login'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'User created'
      redirect_to root_path, notice: ''
    else
      flash[:alert] = 'Invalid user'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
  end

end

app/controllers/users/products_controller.rb
class Users::ProductsController < ApplicationController
  require 'validators/product_validator'
  before_action :authorize
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :find_user

  def index
    @products = @user.products
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    product = Product.new(product_params)
    product.user = @user
    product_validator = ProductValidator.new(product)
    @product = product_validator.create
    if product_validator.saved?
      NewProductWorker.perform_async(@user.id, @product.id)
      redirect_to user_product_path(@user, @product), notice: 'Product was successfully created.'
    else
      render :new
    end

  end

  def update
    if @product.update(product_params)
      redirect_to user_product_path(@user, @product), notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to users_products_url, notice: 'Product was successfully destroyed.'
  end

  private
    def find_user
      @user = User.find(params[:user_id])
      redirect_to user_products_path(current_user) if current_user.id != @user.id
    end

    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image_url)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'User created'
      redirect_to root_path, notice: ''
      SignupMailerWorker.perform_async(@user.id)
    else
      flash[:alert] = 'Invalid user'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users/products_helper.rb
module Users::ProductsHelper
end

app/views/home/index.html.haml
.jumbotron
  %h3.text-center Tianguis
  .text-center
    = link_to 'Sign up', signup_path, class: 'btn btn-primary'
    = link_to 'Sign in', login_path, class: 'btn btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tianguis
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if current_user
      = nav_bar responsive: true do
        = menu_group do
          = menu_item "Feed", products_path
          = menu_item "Mis productos", user_products_path(current_user)
        = menu_group pull: :right do
          = menu_item "Logout", logout_path
    .container
      = bootstrap_flash
      = yield

app/views/products/_product.html.haml
.col-md-3
  .panel.panel-default
    .panel.panel-heading
      = link_to product.name, product_path(product)
    .panel-body
      %p
        User:
        = product.user.user_name
      %p
        Description:
        = product.description
      %p
        Price:
        = product.price
      %p
        Image:
        = product.image_url

app/views/products/index.html.haml
%h1 Listing products

= render partial: @products

app/views/products/show.html.haml
%p
  = @product.name
%p
  = @product.description
%p
  = @product.price
%p
  = @product.image_url

= link_to 'Back', products_path

app/views/users/new.html.haml
%h3.text-center Sign up

= simple_form_for @user, url: '/signup' do |f|
  = f.input :user_name
  = f.input :email, placeholder: 'user@domain.com'
  = f.input :password, hint: 'Minimum length 6.'
  = f.input :password_confirmation
  = f.button :submit

app/views/users/products/_form.html.haml
= simple_form_for([@user, @product]) do |f|
  = f.error_notification
  = f.error :base

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :price
    = f.input :image_url

  .form-actions
    = f.button :submit

app/views/users/products/_product.html.haml
.col-md-3
  .panel.panel-default
    .panel-heading
      = link_to product.name, user_product_path(@user, product)
    .panel-body
      %p
        Description:
        = product.description
      %p
        Price:
        = product.price
      %p
        Image url:
        = product.image_url

app/views/users/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', user_products_path(@user)

app/views/users/products/index.html.haml
%h1 Listing Products feed

= render partial: @products

= link_to 'New', new_user_product_path(@user)

app/views/users/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', user_products_path

app/views/users/products/show.html.haml
%p
  = @product.name
%p
  = @product.description
%p
  = @product.price
%p
  = @product.image_url
= link_to 'Edit', edit_user_product_path(@user, @product)
\|
= link_to 'Back', user_products_path(@user)